
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class ViewSong(Frame):
    def __init__(self, parent, controller=None, *args, **kwargs):
        Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent

        self.configure(bg="#343638")

        self.canvas = Canvas(
            self,
            bg = "#191B29",
            height = 140,
            width = 400,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = self.canvas.create_image(
            231.0,
            112.0,
            image=self.image_image_1
        )

        self.image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = self.canvas.create_image(
            383.0,
            113.0,
            image=self.image_image_2
        )

        self.canvas.create_text(
            96.0,
            27.0,
            anchor="nw",
            text="Song title by",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.image_image_3 = PhotoImage(
            file=relative_to_assets("image_3.png"))
        image_3 = self.canvas.create_image(
            48.0,
            53.0,
            image=self.image_image_3
        )

        self.canvas.create_text(
            96.0,
            44.0,
            anchor="nw",
            text="Artist",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.canvas.create_text(
            96.0,
            59.0,
            anchor="nw",
            text="Mapped by mapper",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.image_image_4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        image_4 = self.canvas.create_image(
            321.0,
            115.0,
            image=self.image_image_4
        )

        self.canvas.create_text(
            276.0,
            100.0,
            anchor="nw",
            text="395.90 pp",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.canvas.create_text(
            192.0,
            100.0,
            anchor="nw",
            text="93.46%",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.image_image_5 = PhotoImage(
            file=relative_to_assets("image_5.png"))
        image_5 = self.canvas.create_image(
            166.0,
            113.0,
            image=self.image_image_5
        )

        self.canvas.create_text(
            144.0,
            100.0,
            anchor="nw",
            text="X 3",
            fill="#FF0000",
            font=("Inter Bold", 16 * -1)
        )

        self.canvas.create_text(
            15.0,
            103.0,
            anchor="nw",
            text="3mo ago",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

if __name__ == "__main__":
    root = Tk()

    root.geometry("1100x300")
    
    canvas = Canvas(root)
    scrollbar = Scrollbar(root, orient="vertical", command=canvas.yview)
    papa_frame = Frame(canvas)

    left_frame = Frame(papa_frame)

    PlayerFrame1 = ViewSong(left_frame, width=400, height=140)
    PlayerFrame1.grid(row=0)

    PlayerFrame2 = ViewSong(left_frame, width=400, height=140)
    PlayerFrame2.grid(row=1)

    PlayerFrame3 = ViewSong(left_frame, width=400, height=140)
    PlayerFrame3.grid(row=2)

    left_frame.grid(column=0)

    right_frame = Frame(papa_frame)

    PlayerFrame1 = ViewSong(right_frame, width=400, height=140)
    PlayerFrame1.grid(row=0)

    PlayerFrame2 = ViewSong(right_frame, width=400, height=140)
    PlayerFrame2.grid(row=1)

    PlayerFrame3 = ViewSong(right_frame, width=400, height=140)
    PlayerFrame3.grid(row=2)

    right_frame.grid(row=0, column=1)

    papa_frame.bind(
        "<Configure>",
        lambda e: canvas.configure(
            scrollregion=canvas.bbox("all")
        )
    )

    canvas.create_window((0, 0), window=papa_frame, anchor="nw")
    canvas.configure(yscrollcommand=scrollbar.set)
    canvas.configure(bg="#343638")
    canvas.pack(side="left", fill="both", expand=True)
    scrollbar.pack(side="right", fill="y")

    root.resizable(False, False)
    root.mainloop()