# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os
from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Canvas, Button, PhotoImage, Toplevel

import api
from LeaderGraph.LeaderGraphFrame import LeaderGraphWidget
from Player1.PlayerFrame import PlayerWidget1
from Player2.PlayerFrame import PlayerWidget2

ASSETS_PATH = os.path.dirname(__file__)
ASSETS_PATH = os.path.join(ASSETS_PATH, 'assets/frame0')

global LeaderGraph1

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def mainWindow():
    MainWindow()

class MainWindow(Toplevel):

    def __init__(self, *args, **kwargs):
        Toplevel.__init__(self, *args, **kwargs)
        global LeaderGraph1

        self.geometry("1220x820")
        self.configure(bg="#6F6F6F")
        self.title('Beat Saber Score Comparator')
        self.iconbitmap(relative_to_assets('BSSC.ico'))

        emptyList = []
        plUser = api.User( 0000, 'temp', 'us', 0000, 10000, 10000, 87, 87, 'https://i.imgur.com/x11FQnw.png', emptyList)

        api.Player1 = plUser
        api.Player2 = plUser

        LeaderGraph1 = LeaderGraphWidget(self, bg="#343638", width=1113, height=500)
        PlayerFrame1 = PlayerWidget1(api.Player1, self, "#B71C1C", bg="#343638", width=540, height=240)
        PlayerFrame2 = PlayerWidget2(api.Player2, self, "#003BFF", bg="#343638", width=540, height=240)

        self.canvas = Canvas(
            self,
            bg="#6F6F6F",
            height=1024,
            width=1220,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        self.canvas.place(x=0, y=0)

        self.canvas.create_rectangle(
            83.5, 309.0, 83.5 + 1113.0, 309.0 + 500.0, fill="#343638", outline=""
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            self.canvas,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: LeaderGraph1.navigate('leaderboard'),
            cursor='hand2', activebackground="#6F6F6F",
            relief="flat"
        )
        self.button_1.place(
            x=16.0,
            y=309.0,
            width=45.0,
            height=45.0
        )


        button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        self.button_2 = Button(
            self.canvas,
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: LeaderGraph1.navigate('graph'),
            cursor='hand2', activebackground="#6F6F6F",
            relief="flat"
        )
        self.button_2.place(
            x=16.0,
            y=369.0,
            width=45.0,
            height=45.0
        )

        button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        self.button_3 = Button(
            self.canvas,
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: LeaderGraph1.left_sortByUnplayed(),
            cursor='hand2', activebackground="#6F6F6F",
            relief="flat"
        )
        self.button_3.place(
            x=489.0,
            y=265.0,
            width=128.0,
            height=32.0
        )

        button_image_4 = PhotoImage(
            file=relative_to_assets("button_4.png"))
        self.button_4 = Button(
            self.canvas,
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: LeaderGraph1.left_sortByRecent(),
            cursor='hand2', activebackground="#6F6F6F",
            relief="flat"
        )
        self.button_4.place(
            x=347.0,
            y=265.0,
            width=128.0,
            height=32.0
        )

        button_image_5 = PhotoImage(
            file=relative_to_assets("button_5.png"))
        self.button_5 = Button(
            self.canvas,
            image=button_image_5,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: LeaderGraph1.left_sortByPP(),
            cursor='hand2', activebackground="#6F6F6F",
            relief="flat"
        )
        self.button_5.place(
            x=205.0,
            y=265.0,
            width=128.0,
            height=32.0
        )

        button_image_6 = PhotoImage(
            file=relative_to_assets("button_6.png"))
        self.button_6 = Button(
            self.canvas,
            image=button_image_6,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: LeaderGraph1.right_sortByUnplayed(),
            cursor='hand2', activebackground="#6F6F6F",
            relief="flat"
        )
        self.button_6.place(
            x=1062.0,
            y=261.0,
            width=128.0,
            height=32.0
        )

        button_image_7 = PhotoImage(
            file=relative_to_assets("button_7.png"))
        self.button_7 = Button(
            self.canvas,
            image=button_image_7,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: LeaderGraph1.right_sortByRecent(),
            cursor='hand2', activebackground="#6F6F6F",
            relief="flat"
        )
        self.button_7.place(
            x=920.0,
            y=261.0,
            width=128.0,
            height=32.0
        )

        button_image_8 = PhotoImage(
            file=relative_to_assets("button_8.png"))
        self.button_8 = Button(
            self.canvas,
            image=button_image_8,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: LeaderGraph1.right_sortByPP(),
            cursor='hand2', activebackground="#6F6F6F",
            relief="flat"
        )
        self.button_8.place(
            x=778.0,
            y=261.0,
            width=128.0,
            height=32.0
        )

        # place and raise the player frames on the main window
        PlayerFrame1.place(x=77, y=11, width=540.0, height=240.0)
        PlayerFrame2.place(x=650, y=11, width=540.0, height=240.0)
        LeaderGraph1.place(x=83.5, y=309, width=1120.0, height=500.0)

        PlayerFrame1.tkraise()
        PlayerFrame2.tkraise()

        self.resizable(False, False)
        self.mainloop()

    def refreshLeft(self):
        # print('refreshLeft')
        LeaderGraph1.tkraise()
        LeaderGraph1.left_sortByPP()

    def refreshRight(self):
        # print('refreshRight')
        LeaderGraph1.tkraise()
        LeaderGraph1.left_sortByPP()
        # LeaderGraph1.right_sortByPP()
