# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Listbox, Entry, Text, Button, PhotoImage, END, Frame

import requests
import io
import os
from PIL import Image, ImageTk
import cloudscraper

ASSETS_PATH = os.path.dirname(__file__)
ASSETS_PATH = os.path.join(ASSETS_PATH, 'assets/frame0')


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class RecentPlayer(Frame):
    def __init__(self, parent, controller=None, *args, **kwargs):
        Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent

        self.configure(bg="#343638")

        self.canvas = Canvas(
            self,
            bg="#343638",
            height=240,
            width=540,
            bd=0,
            highlightthickness=0,
        )

        self.canvas.place(x=0, y=0)

        self.recentListbox = Listbox(
            self.canvas,
            x=20.0,
            y=10.0,
            height=180,
            width=500,
            relief="sunken",
            font=("Inter", 16 * -1)
        )
        self.recentListbox.insert(END, 'Acerola 76561198002500746')

        self.recentListbox.place(
            x=20.0,
            y=10.0,
            height=180,
            width=500,
        )

        self.button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            self.canvas,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )

        self.button_1.place(
            x=176.0,
            y=200.0,
            width=186.0,
            height=30.0
        )

        self.button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
        self.button_2 = Button(
            self.canvas,
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat"
        )

        self.button_2.place(
            x=368.0,
            y=200.0,
            width=162.0,
            height=30.0
        )
