
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("400x140")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    height = 140,
    width = 400,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    200.0,
    70.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    231.0,
    112.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    383.0,
    113.0,
    image=image_image_3
)

canvas.create_text(
    96.0,
    27.0,
    anchor="nw",
    text="Song title by",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    48.0,
    53.0,
    image=image_image_4
)

canvas.create_text(
    96.0,
    44.0,
    anchor="nw",
    text="Artist",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    96.0,
    59.0,
    anchor="nw",
    text="Mapped by mapper",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    321.0,
    115.0,
    image=image_image_5
)

canvas.create_text(
    276.0,
    100.0,
    anchor="nw",
    text="395.90 pp",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    192.0,
    100.0,
    anchor="nw",
    text="93.46%",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    166.0,
    113.0,
    image=image_image_6
)

canvas.create_text(
    144.0,
    100.0,
    anchor="nw",
    text="X 3",
    fill="#FF0000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    15.0,
    103.0,
    anchor="nw",
    text="3mo ago",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
