
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
import api
from datetime import datetime
from dateutil import relativedelta

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class ViewSong(Frame):
    image_1 = None
    image_2 = None
    image_4 = None
    image_5 = None

    songIcons = {}

    def __init__(self, parent, song, controller=None, *args, **kwargs):
        Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent

        #only load these once
        if ViewSong.image_1 == None:
            ViewSong.image_1 = PhotoImage( file=relative_to_assets("image_1.png"))
            ViewSong.image_2 = PhotoImage( file=relative_to_assets("image_2.png"))
            ViewSong.image_4 = PhotoImage( file=relative_to_assets("image_4.png"))
            ViewSong.image_5 = PhotoImage( file=relative_to_assets("image_5.png"))


        self.canvas = Canvas(
            self,
            bg = "#343638",
            height = 117,
            width = 540,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.image_image_1 = ViewSong.image_1 
        self.canvas.create_image(
            270.0,
            58.0,
            image=self.image_image_1
        )

        self.image_image_2 = ViewSong.image_2 
        self.canvas.create_image(
            489.0,
            55.0,
            image=self.image_image_2
        )

        self.canvas.create_text(
            93.0,
            19.0,
            anchor="nw",
            text=f"{song.name}",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        if song.id not in ViewSong.songIcons:
            ViewSong.songIcons[song.id] = api.getIcon(song.image, w=77, h=77) 

        self.image_image_3 = ViewSong.songIcons[song.id]
        image_3 = self.canvas.create_image(
            48.0,
            53.0,
            image=self.image_image_3
        )

        self.canvas.create_text(
            93.0,
            36.0,
            anchor="nw",
            text=f"by {song.artist}",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.canvas.create_text(
            93.0,
            51.0,
            anchor="nw",
            text=f"Mapped by {song.mapper}",
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.image_image_4 = ViewSong.image_4 
        self.canvas.create_image(
            485.0,
            25.0,
            image=self.image_image_4
        )

        self.canvas.create_text(
            485.0,
            25.0,
            anchor="center",
            text="%.2f pp" % song.pp,
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.canvas.create_text(
            490.0,
            56.5,
            anchor="center",
            text="%.2f%%" % song.accuracy,
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.image_image_5 = ViewSong.image_5 
        self.canvas.create_image(
            507.0,
            89.0,
            image=self.image_image_5
        )

        self.canvas.create_text(
            507.0,
            89.5,
            anchor="center",
            text=f"X {song.misses}",
            fill="#FF0000",
            font=("Inter Bold", 16 * -1)
        )

        delta = relativedelta.relativedelta(datetime.now(), song.timeSet)
        if delta.years > 0:
            time_str = f'{delta.years}'
            if delta.years == 1:
                time_str += ' year'
            else:
                time_str += ' years'
        elif delta.months > 0:
            time_str = f'{delta.months}'
            if delta.months == 1:
                time_str += ' month'
            else:
                time_str += ' months'
        else:
            time_str = f'{delta.days}'
            if delta.days == 1:
                time_str += ' day'
            else:
                time_str += ' days'
        time_str += ' ago'
        self.canvas.create_text(
            15.0,
            94.0,
            anchor="nw",
            text=time_str,
            fill="#FFFFFF",
            font=("Inter", 16 * -1)
        )

        self.canvas.create_text(
            93.0,
            70.0,
            anchor="nw",
            text=f"{song.stars} stars",
            fill="#DB00FF",
            font=("Inter", 16 * -1)
        )

# TODO load images upfront
def build_song_frame(frame, songlist):
    for i in range(len(songlist)):
        song = songlist[i]
        if song != None:
            PlayerFrame = ViewSong(frame, song, width=540, height=117)
        else:
            PlayerFrame = Frame(frame, width=540, height=117, bg='#343638')
        PlayerFrame.grid(row=i, padx=5, pady=5)

class ViewSongTable(Frame):

    def __init__(self, parent, controller=None, *args, **kwargs):
        Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent

        canvas = Canvas(parent)
        scrollbar = Scrollbar(parent, orient="vertical", command=canvas.yview)
        self.papa_frame = Frame(canvas)
        self.left_frame = None
        self.right_frame = None

        length = 20
        self.left_songlist = api.Player1.songList
        self.right_songlist = api.Player2.songList

        self.left_sortByPP()

        self.papa_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(
                scrollregion=canvas.bbox("all")
            )
        )

        canvas.create_window((0, 0), window=self.papa_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)
        canvas.configure(bg="#343638")
        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")

    def build_frames(self, left_list, right_list):
        if self.left_frame != None:
            self.left_frame.destroy()
        if self.right_frame != None:
            self.right_frame.destroy()

        self.left_frame = Frame(self.papa_frame)
        self.left_frame.configure(bg="#343638")
        build_song_frame(self.left_frame, left_list)
        self.left_frame.grid(row=0, column=0)

        self.right_frame = Frame(self.papa_frame)
        self.right_frame.configure(bg="#343638")
        build_song_frame(self.right_frame, right_list)
        self.right_frame.grid(row=0, column=1)
    
    def left_sortByPP(self):
        self.updateLists()
        left_list = api.sortByPP(self.left_songlist)
        right_list = api.getCorrespondingList(left_list, self.right_songlist)
        self.build_frames(left_list, right_list)

    def left_sortByRecent(self):
        self.updateLists()
        left_list = api.sortByRecent(self.left_songlist)
        right_list = api.getCorrespondingList(left_list, self.right_songlist)
        self.build_frames(left_list, right_list)

    def left_sortByUnplayed(self):
        self.updateLists()
        left_list = api.sortByUnplayed(self.left_songlist, self.right_songlist)
        right_list = api.getCorrespondingList(left_list, self.right_songlist)
        self.build_frames(left_list, right_list)

    def right_sortByPP(self):
        self.updateLists()
        right_list = api.sortByPP(self.right_songlist)
        left_list = api.getCorrespondingList(right_list, self.left_songlist)
        self.build_frames(left_list, right_list)

    def right_sortByRecent(self):
        self.updateLists()
        right_list = api.sortByRecent(self.right_songlist)
        left_list = api.getCorrespondingList(right_list, self.left_songlist)
        self.build_frames(left_list, right_list)

    def right_sortByUnplayed(self):
        self.updateLists()
        right_list = api.sortByUnplayed(self.right_songlist, self.left_songlist)
        left_list = api.getCorrespondingList(right_list, self.left_songlist)
        self.build_frames(left_list, right_list)

    def updateLists(self):
        self.left_songlist = api.Player1.songList
        self.right_songlist = api.Player2.songList