# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import requests
import io
import os
from PIL import Image, ImageTk
import cloudscraper

ASSETS_PATH = os.path.dirname(__file__)
ASSETS_PATH = os.path.join(ASSETS_PATH, 'assets/frame0')


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("540x240")
window.configure(bg="#343638")

canvas = Canvas(
    window,
    bg="#343638",
    height=240,
    width=540,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)

canvas.create_text(
    10.0,
    80.0,
    anchor="nw",
    text="Accepts Usernames, Scoresaber URLs, and Scoresaber IDs",
    fill="#A2A4A6",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    10.0,
    0.0,
    anchor="nw",
    text="Enter Player Here",
    fill="#FFFFFF",
    font=("Inter", 36 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=10.0,
    y=204.0,
    width=190.0,
    height=25.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=260.0,
    y=200.0,
    width=115.0,
    height=29.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=378.0,
    y=199.0,
    width=152.0,
    height=30.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    270.0,
    62.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=10.0,
    y=46.0,
    width=520.0,
    height=30.0
)

canvas = Canvas(
    window,
    bg="#343638",
    height=240,
    width=540,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

window.resizable(False, False)
window.mainloop()
